version: '3.5'

services:

  jenkins:
    image: docker.io/hoto/jenkinsfile-examples
    build: .
    ports:
    - target: 8080
      published: 8080
    networks:
    - jenkins-network
    tty: true

  jenkinsfile-loader:
    image: docker.io/hoto/jenkinsfile-loader
    environment:
      JENKINS_URL: 'http://jenkins:8080'
      JENKINSFILES_DIR: '/usr/local/src/jenkinsfiles'
      DEBUG: 'false'
    volumes:
    - type: bind
      source: ${PWD}/jenkinsfiles
      target: /usr/local/src/jenkinsfiles
      read_only: true
    depends_on:
    - jenkins
    networks:
    - jenkins-network
    tty: true


networks:
  jenkins-network:
